Update publish-to-test-matrix-controller.yml

diff --git a/.github/workflows/publish-to-test-matrix-controller.yml b/.github/workflows/publish-to-test-matrix-controller.yml
--- a/.github/workflows/publish-to-test-matrix-controller.yml
+++ b/.github/workflows/publish-to-test-matrix-controller.yml
@@ -60,7 +60,7 @@ jobs:
         run: |
           OPEN_PR_COUNT=$(gh pr list --search 'milestone:"${{ inputs.MILESTONE_TITLE }}"' --state open --json number | jq '. | length')
           if [ "$OPEN_PR_COUNT" -gt 0 ]; then
-           echo "::error::There are $OPEN_PR_COUNT open PRs in the milestone ${{ inputs.MILESTONE_TITLE }}.Exiting." && exit 1
+           echo "::error::Cannot continue when there is $OPEN_PR_COUNT open PR(s) in the milestone ${{ inputs.MILESTONE_TITLE }}.Exiting." && exit 1
           else
            echo "No Open PRs found in the milestone ${{ inputs.MILESTONE_TITLE }}.Continuing."
           fi
